### ISSUE TITLE
'RecipeSerializer' object has no attribute '_serialize_yields'

### ISSUE THREAD

**Issue by tom-anders** [tstehr/recipemd-serve#1]
Using the main branch of this repo and the latest recipemd version from pip.
```
Traceback (most recent call last):
  File "/home/tom/.local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/tom/.local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/tom/.local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tom/.local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tom/.local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tom/.local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tom/.local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tom/.local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tom/.local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tom/.local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tom/Documents/recipemd-serve/recipemd-serve/main.py", line 118, in download_file
    yields=recipe_serializer._serialize_yields(recipe.yields),
AttributeError: 'RecipeSerializer' object has no attribute '_serialize_yields'
```

**Comment by tstehr** [comment]
True, this is still very much in development. I didn't yet want to commit to a public API in `recipemd`, since I'd have to support that forever or risk breaking compatibility.

I've pushed the work in progress commit, you can check it out in the [serialize-recipe-parts branch](https://github.com/tstehr/RecipeMD/tree/serialize-recipe-parts). If you want to experiment with it, you can install that via

```
pip install git+https://github.com/tstehr/RecipeMD.git@serialize-recipe-parts
```

**Comment by tom-anders** [comment]
Cool, thanks!
